import { createFileRoute } from "@tanstack/react-router";
import { AppShell } from "@/components/app/AppShell";
import { PageHeader } from "@/components/app/PageHeader";
import { Button } from "@/components/ui/button";
import { Plus, Clock, Target, CheckCircle2 } from "lucide-react";
import { motion } from "framer-motion";

export const Route = createFileRoute("/planner")({
  head: () => ({
    meta: [
      { title: "Study Planner — Neura Learn" },
      { name: "description", content: "Adaptive weekly study plans built by AI, tailored to your goals and calendar." },
      { property: "og:title", content: "Study Planner — Neura Learn" },
      { property: "og:description", content: "Plan smarter with adaptive AI schedules." },
    ],
  }),
  component: Planner,
});

const week = [
  { day: "Mon", tasks: [{ t: "Calculus · Chapter 4", d: "9:00–10:00", done: true }, { t: "Flashcards drill", d: "6:00–6:20", done: true }] },
  { day: "Tue", tasks: [{ t: "Physics mock", d: "10:00–11:30", done: true }] },
  { day: "Wed", tasks: [{ t: "Essay outline", d: "3:00–4:00", done: false }, { t: "Vocab review", d: "8:00–8:20", done: false }] },
  { day: "Thu", tasks: [{ t: "Data structures quiz", d: "5:00–6:00", done: false }] },
  { day: "Fri", tasks: [{ t: "AI 1:1 review", d: "4:30–5:00", done: false }, { t: "History reading", d: "8:00–8:40", done: false }] },
  { day: "Sat", tasks: [{ t: "Weekly deep-work", d: "10:00–12:00", done: false }] },
  { day: "Sun", tasks: [{ t: "Reflection & planning", d: "8:00–8:30", done: false }] },
];

function Planner() {
  return (
    <AppShell>
      <PageHeader
        eyebrow="Study Planner"
        title="This week's plan"
        description="Adaptive, generated by AI, and fitted to your goals."
        actions={
          <>
            <Button variant="outline"><Target className="mr-2 h-4 w-4" /> Adjust goals</Button>
            <Button className="bg-gradient-primary text-white"><Plus className="mr-2 h-4 w-4" /> New task</Button>
          </>
        }
      />

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        {[
          { l: "Tasks scheduled", v: "18" },
          { l: "Completed", v: "7" },
          { l: "Focus hours", v: "12.5" },
          { l: "Est. mastery gain", v: "+9%" },
        ].map((s) => (
          <div key={s.l} className="rounded-2xl border bg-card p-5 shadow-soft">
            <div className="text-xs text-muted-foreground">{s.l}</div>
            <div className="mt-1 text-2xl font-bold">{s.v}</div>
          </div>
        ))}
      </div>

      <div className="mt-6 grid gap-4 lg:grid-cols-7">
        {week.map((d, i) => (
          <motion.div
            key={d.day}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.04 }}
            className="rounded-2xl border bg-card p-4 shadow-soft"
          >
            <div className="mb-3 flex items-center justify-between">
              <div className="text-sm font-semibold">{d.day}</div>
              <span className="text-xs text-muted-foreground">{d.tasks.length}</span>
            </div>
            <div className="space-y-2">
              {d.tasks.map((t, j) => (
                <div key={j} className="rounded-xl border p-3">
                  <div className="flex items-start justify-between gap-2">
                    <div className="min-w-0">
                      <div className="truncate text-sm font-medium">{t.t}</div>
                      <div className="mt-1 flex items-center gap-1 text-[11px] text-muted-foreground">
                        <Clock className="h-3 w-3" /> {t.d}
                      </div>
                    </div>
                    {t.done && <CheckCircle2 className="h-4 w-4 shrink-0 text-success" />}
                  </div>
                </div>
              ))}
              {d.tasks.length === 0 && (
                <div className="rounded-xl border border-dashed p-3 text-center text-xs text-muted-foreground">
                  Free day
                </div>
              )}
            </div>
          </motion.div>
        ))}
      </div>
    </AppShell>
  );
}
